### ISSUE TITLE
can kegg-pull parse the text flat files?

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/kegg_pull#219]
I'm guessing that's more part of the API, but it seems like it would be awesome to be able to spit out a JSONized versions of the flat text files for compounds where all the information is already parsed out into the individual pieces.

**Comment by erikhuck** [comment]
@rmflight Are you thinking about something like [this](https://github.com/lozuponelab/KEGG_parser/tree/master)?

**Comment by rmflight** [comment]
Looking at the code, that's likely a nice candidate for this. Or I might refactor my code into a proper little r-package for parsing those files as well.

Thanks @erikhuck !
